### ISSUE TITLE
[Proposal]: change Keymap

### ISSUE THREAD

**Issue by gabriel-caruso** [HiDeoo/toggler#3]
Atom now has the keymap `Ctrl+R` for method search. So, why don't make `Alt+R` for all OSs?

**Comment by HiDeoo** [comment]
Is this an upcoming change? 

By looking at the Atom default [symbols-view keymaps](https://github.com/atom/symbols-view/blob/3333aa402c14a50f5a96e6da4f2a3bd8477e9b22/keymaps/symbols-view.cson), `ctrl-r` is still used only on Windows & Linux while `cmd-r` is used on macOS.

I can't find anything either in the Atom [default keymaps](https://github.com/atom/atom/tree/23c6dcb5284995726840a1afbaa69c891c9193e7/keymaps) regarding `ctrl-r`.

**Comment by gabriel-caruso** [comment]
Sorry, I explained myself wrong.

Again: `Ctrl+R` is used by Atom to search method in Linux and Windows(L7 and L10 of [symbos-view keymap](https://github.com/atom/symbols-view/blob/master/keymaps/symbols-view.cson#L10)), and in the Toggler Readme file, [this is used in Linux](https://github.com/HiDeoo/toggler/blame/master/README.md#L26). 

So, my proposal is to unify this: make the default keymap for Toggler as `Alt+R` for all OSs, what do you thing?

**Comment by HiDeoo** [comment]
Gotcha, didn't catch that at first, my bad.

For a little bit of history, the initial shortcut was `Ctrl + R` on all platforms and I changed it on Windows because I got reports it was triggering a Windows menu or something (I don't have any Windows machine so can't test).

Regarding macOS, I'll keep `Ctrl + R` as it's not mapped to anything by default by Atom and easier to use in my opinion.

I'll ask some Linux users and test on various Linux distributions if `Alt + R` is not mapped to anything OS related and if it's not the case, I'll update the default shortcut on Linux to be `Alt + R` too so it'll avoid the default conflict with Atom keymap. Good call 👍

**Comment by Nfinished** [comment]
Did Linux ever actually get changed to `Alt+R`? It's still `Ctrl + R` for me. Additionally, `Ctrl+R+R` is a hotkey for another package I have installed, so Toggler will only fire if I complete the chord by moving my cursor after a `Ctrl + R`.

**Comment by HiDeoo** [comment]
@Nfinished Just changed the default shortcut for Linux in `v0.3.1` which is now available.

**Comment by Nfinished** [comment]
Awesome! Thanks a lot!
